### ISSUE TITLE
error: settings up client, please white help me please

### ISSUE THREAD

**Issue by medaion** [AlaskaVet/Tanoa_Life.Tanoa#1]
Hi, would it be possible to you to add the file or tanoa.sql Altis.sql.
You used to you logged on the server.
For me I get an error: settings up client, please white

Sorry for my English, I use google translate.
  I am french .

Cordialement , medaion

**Comment by AlaskaVet** [comment]
As of right now that's not released to the public. Only for privet party's.

**Comment by medaion** [comment]
A ok

**Comment by medaion** [comment]
A ok
